#!/usr/bin/env python3
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT / "python"))
sys.path.insert(0, str(ROOT / "signatures" / "tools"))

from phenosigdb_maintainer.build import main

if __name__ == "__main__":
    main()
