#!/usr/bin/env python3
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "python"))
sys.path.insert(0, str(ROOT / "signatures" / "tools"))

from phenosigdb_maintainer.external_imports.__main__ import main

if __name__ == "__main__":
    main()
